### ISSUE TITLE
Syntax checking is broken

### ISSUE THREAD

**Issue by akatechis** [rust-lang/rust-enhanced#241]
### Sublime Text Version
Sublime Text 3 (Build 3143)

### Rust Enhanced Version
2.7.0

### Operating system
OS Name: Microsoft Windows 10 Pro
OS Build: 15063.850

In the console, I see the following message:
```
Syntax Check +137.676 Rust running: ['cargo', 'metadata', '--no-deps']
Exception in thread Syntax Check:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "rust.rust_thread in C:\Users\Alexandros\AppData\Roaming\Sublime Text 3\Installed Packages\Rust Enhanced.sublime-package", line 91, in _thread_run
  File "SyntaxCheckPlugin in C:\Users\Alexandros\AppData\Roaming\Sublime Text 3\Installed Packages\Rust Enhanced.sublime-package", line 108, in run
  File "SyntaxCheckPlugin in C:\Users\Alexandros\AppData\Roaming\Sublime Text 3\Installed Packages\Rust Enhanced.sublime-package", line 143, in get_rustc_messages
TypeError: get_command() got multiple values for argument 'initial_settings'
```

I tried uninstalling and reinstalling to see if there was some corrupt data or something that might be at fault, but it made no difference.

**Comment by ehuss** [comment]
I suspect it has something to do with how Package Control updates the package.  Have you tried restarting Sublime?

**Comment by Jayflux** [comment]
Im on Windows 10, it seems to be working ok for me

**Comment by ehuss** [comment]
I'm able to reproduce this when upgrading from an older version of Rust Enhanced.  I've opened wbond/package_control#1325 to see if I can get down to the underlying problem and figure out how to avoid it in the future.

For now, the workaround is to restart Sublime after updating Rust Enhanced.

**Comment by ehuss** [comment]
Rust Enhanced should now work properly after being updated (#267).
