### ISSUE TITLE
NoneType errors in Sublime console

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust-enhanced#343]
### Sublime Text Version
Sublime Text 3 (Build 3175)

### Rust Enhanced Version
v2.16.0

& rustc 1.29.0-beta.9 (b4ec8d46e 2018-09-01)

### Operating system
macOS 10.14 Beta (18A377a)

### Actual behavior
I'm seeing a bunch of errors in the Sublime's console. I'm not sure if it actually breaks any functionality, but perhaps some `None` checks are needed:

Rust Error: [Error loading JSON from rust: '{"features":[],"filenames":["/www/project/target/debug/libproject-7236f13f0d58f0c6.rmeta"],"fresh":false,"package_id":"project 0.8.5 (path+file:///www/project)","profile":{"debug_assertions":true,"debuginfo":2,"opt_level":"1","overflow_checks":true,"test":true},"reason":"compiler-artifact","target":{"crate_types":["bin"],"edition":"2015","kind":["bin"],"name":"project","src_path":"/www/project/src/bin/project.rs"}}\n']
…
Exception in thread Syntax Check: Stdout:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Rust Enhanced.sublime-package/rust/rust_proc.py", line 283, in _read_stdout
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Rust Enhanced.sublime-package/rust/rust_proc.py", line 321, in _cleanup
AttributeError: 'NoneType' object has no attribute 'time'
…
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Rust Enhanced.sublime-package/SyntaxCheckPlugin.py", line 98, in <lambda>
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Rust Enhanced.sublime-package/SyntaxCheckPlugin.py", line 98, in update_status
AttributeError: 'NoneType' object has no attribute 'set_timeout'
…
Exception in thread Syntax Check:
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Rust Enhanced.sublime-package/rust/rust_thread.py", line 91, in _thread_run
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/Rust Enhanced.sublime-package/SyntaxCheckPlugin.py", line 84, in run
AttributeError: 'NoneType' object has no attribute 'messages_finished'

**Comment by ehuss** [comment]
Hm, looks like Python has gotten in a confused state.  Can you try restarting Sublime and see if it continues?  I've never seen anything quite like that.

**Comment by kornelski** [comment]
Yup, it's gone after restart.
