### ISSUE TITLE
Rust check failing for unknown reason.

### ISSUE THREAD

**Issue by c-edw** [rust-lang/rust-enhanced#391]
### Sublime Text Version
`Sublime Text Build 3207`

### Rust Enhanced Version
`v2.20.0`

### Operating system
`Fedora 29`

### Expected behavior
A Rust compile check to be carried out.

### Actual behavior
In the bottom right of Sublime Text, an error message is shown: `Rust check failed, see console or debug log`. When I check `Rust: Open Debug Log`, an empty file is opened.

### Steps to reproduce

- Open a fresh Rust project (initialised with `cargo init`)
- Open the project in Sublime Text (with `subl .`)
- Navigate to `main.rs`
- Hit `Ctrl+S` to attempt a check

### References
N/A

**Comment by ehuss** [comment]
Was there anything in Sublime's console (View > Show Console)?

**Comment by c-edw** [comment]
Ah, yes:
```
Exception in thread Syntax Check:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/home/cedwards/.config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package/rust/rust_thread.py", line 91, in _thread_run
    self.run()
  File "/home/cedwards/.config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package/SyntaxCheckPlugin.py", line 90, in run
    rc = self.get_rustc_messages()
  File "/home/cedwards/.config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package/SyntaxCheckPlugin.py", line 169, in get_rustc_messages
    metadata = util.get_cargo_metadata(self.window, self.cwd, toolchain=toolchain)
  File "/home/cedwards/.config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package/rust/util.py", line 136, in get_cargo_metadata
    cwd=cwd)
  File "/home/cedwards/.config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package/rust/rust_proc.py", line 97, in slurp_json
    rc, listener = _slurp(window, cmd, cwd)
  File "/home/cedwards/.config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package/rust/rust_proc.py", line 79, in _slurp
    p.run(window, cmd, cwd, listener)
  File "/home/cedwards/.config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package/rust/rust_proc.py", line 197, in run
    USER_SHELL_ENV = shellenv.get_env()[1]
  File "/home/cedwards/.config/sublime-text-3/Packages/shellenv/all/shellenv/_linux/__init__.py", line 51, in get_env
    _, login_env = get_shell_env(shell, for_subprocess=for_subprocess)
  File "/home/cedwards/.config/sublime-text-3/Packages/shellenv/all/shellenv/_posix.py", line 44, in get_shell_env
    _, shell_name = shell.rsplit('/', 1)
ValueError: need more than 1 value to unpack
```

**Comment by c-edw** [comment]
It looks like this is I have set my shell (zsh) improperly such that the value of `$SHELL` is just `zsh`. This code assumes that `$SHELL` is absolute path. Ironically I just noticed this a few minutes ago whilst working on my own project.
Perhaps we could search for the value of `$SHELL` in `/bin` or something if it's not an absolute path.

**Comment by ehuss** [comment]
That is part of the [`shellenv`](https://github.com/codexns/shellenv) package, so Rust Enhanced doesn't have any control over that.  There is a config value `rust_include_shell_env` for disabling shell env detection if there are any problems.  Given that it sounds like you figured out your problem, and there's not much we can do on this end, I'm going to close out this issue.

**Comment by c-edw** [comment]
My mistake, you're correct. I'll file this issue with them. Thanks for your help.
