### ISSUE TITLE
Syntax checking not working

### ISSUE THREAD

**Issue by jonahbron** [rust-lang/rust-enhanced#392]
I just installed Rust Enhanced, but the syntax checking isn't working for me.  Cargo and rustc are both in my path (set up by .bashrc), and I can open a terminal and run either of them just fine.  But Rust Enhanced doesn't seem to be able to find them.  The core of the error is:

```Command '['rustc', '--version']' returned non-zero exit status 1```

Running `rustc --version` in a terminal window works perfectly.  I've made no changes to the package's configuration.  How can I get it to see them?

### Sublime Text Version
Sublime Text 3 (Build 3207)

### Rust Enhanced Version
2.20.0

### Operating system
A good example is:
OS Name	Clear Linux

### Expected behavior
Syntax check should show errors

### Actual behavior
The console outputs:
```
Exception in thread Syntax Check:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/home/jonah/.var/app/com.sublimetext.three/config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package/rust/rust_thread.py", line 91, in _thread_run
    self.run()
  File "/home/jonah/.var/app/com.sublimetext.three/config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package/SyntaxCheckPlugin.py", line 90, in run
    rc = self.get_rustc_messages()
  File "/home/jonah/.var/app/com.sublimetext.three/config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package/SyntaxCheckPlugin.py", line 180, in get_rustc_messages
    force_json=True, metadata=metadata)
  File "/home/jonah/.var/app/com.sublimetext.three/config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package/rust/cargo_settings.py", line 480, in get_command
    rustc_version = util.get_rustc_version(self.window, working_dir, toolchain=toolchain)
  File "/home/jonah/.var/app/com.sublimetext.three/config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package/rust/util.py", line 56, in get_rustc_version
    output = rust_proc.check_output(window, cmd, cwd)
  File "/home/jonah/.var/app/com.sublimetext.three/config/sublime-text-3/Installed Packages/Rust Enhanced.sublime-package/rust/rust_proc.py", line 122, in check_output
    raise subprocess.CalledProcessError(rc, cmd, output)
subprocess.CalledProcessError: Command '['rustc', '--version']' returned non-zero exit status 1
```

### Steps to reproduce
1. Open the Sublime Text console
2. Save a file

**Comment by jonahbron** [comment]
It seems this was a problem with the way I restarted Sublimetext.  It mus have been still running in the background, because when I used the File > Quit option and re-opened it, suddenly this problem went away.
