### ISSUE TITLE
Some kind of deadlock when running syntax checking/builds which hangs ST

### ISSUE THREAD

**Issue by JarrettBillingsley** [rust-lang/rust-enhanced#455]
- **Sublime Text Version:** Sublime Text 3 (Build 3211)
- **Rust Enhanced Version:** 2.23.0
- **Operating system:** Mac OS Catalina 10.15.5
- **Expected behavior:** When syntax checking runs, or I build the project, it should work. (It used to work.)
- **Actual behavior:**
	- When syntax checking runs, or I build the project, ST spawns a bash process which uses 100% of one CPU core but does nothing. It uses ~25MB RAM and doesn't seem to do any I/O.
	- From a call stack sampling, the ST plugin container process seems to be stuck on a `poll` call but I can't be sure.
	- This causes ST to hang and be unresponsive until I kill that bash process.
	- But if I kill the bash process, the behavior changes: now when I build, I get this error on the ST console: 
	
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1050, in run_
    return self.run(**args)
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/Rust Enhanced.sublime-package/cargo_build.py", line 53, in run
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/Rust Enhanced.sublime-package/cargo_build.py", line 74, in _detect_auto_build
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/Rust Enhanced.sublime-package/rust/target_detect.py", line 35, in determine_targets
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/Rust Enhanced.sublime-package/rust/util.py", line 136, in get_cargo_metadata
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/Rust Enhanced.sublime-package/rust/rust_proc.py", line 97, in slurp_json
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/Rust Enhanced.sublime-package/rust/rust_proc.py", line 79, in _slurp
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/Rust Enhanced.sublime-package/rust/rust_proc.py", line 234, in run
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
OSError: [Errno 7] Argument list too long
```

This behavior persists until I restart ST.

Rust was installed with `rustup`.

**Comment by officialcjunior** [comment]
I seem to have the same issue here on Arch Linux, as well

**Comment by JarrettBillingsley** [comment]
This seems to be an issue with shellenv, not Rust Enhanced.

https://github.com/codexns/shellenv/issues/3
