### ISSUE TITLE
"FileNotFoundError: [Errno 2] No such file or directory: 'cargo'"

### ISSUE THREAD

**Issue by eboatwright** [rust-lang/rust-enhanced#502]
### Sublime Text Version
Sublime Text (Build 4143)

### Rust Enhanced Version
v2.25.0

### Cargo version
1.66.0 (d65d197ad 2022-11-15)

### RustC version
1.66.0 (69f9c33d7 2022-12-12)

### Operating system
Ubuntu 22.04

### Expected behavior
Error highlighting

### Actual behavior
I got this error in the console:
FileNotFoundError: [Errno 2] No such file or directory: 'cargo'

### Additional info
I've tried deleting my target and Cargo.lock files and trying again, I've tried rebuilding with cargo build, and I'm not using any packages

### Full error message
Exception in thread Syntax Check:
Traceback (most recent call last):
  File "./python3.3/threading.py", line 901, in _bootstrap_inner
  File "./python3.3/threading.py", line 858, in run
  File "/home/USER/.config/sublime-text/Installed Packages/Rust Enhanced.sublime-package/rust/rust_thread.py", line 91, in _thread_run
    self.run()
  File "/home/USER/.config/sublime-text/Installed Packages/Rust Enhanced.sublime-package/SyntaxCheckPlugin.py", line 90, in run
    rc = self.get_rustc_messages()
  File "/home/USER/.config/sublime-text/Installed Packages/Rust Enhanced.sublime-package/SyntaxCheckPlugin.py", line 159, in get_rustc_messages
    metadata = util.get_cargo_metadata(self.window, self.cwd, toolchain=toolchain)
  File "/home/USER/.config/sublime-text/Installed Packages/Rust Enhanced.sublime-package/rust/util.py", line 136, in get_cargo_metadata
    cwd=cwd)
  File "/home/USER/.config/sublime-text/Installed Packages/Rust Enhanced.sublime-package/rust/rust_proc.py", line 97, in slurp_json
    rc, listener = _slurp(window, cmd, cwd)
  File "/home/USER/.config/sublime-text/Installed Packages/Rust Enhanced.sublime-package/rust/rust_proc.py", line 79, in _slurp
    p.run(window, cmd, cwd, listener)
  File "/home/USER/.config/sublime-text/Installed Packages/Rust Enhanced.sublime-package/rust/rust_proc.py", line 234, in run
    stderr=subprocess.STDOUT,
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'cargo'

**Comment by ehuss** [comment]
It looks like `cargo` is not in your PATH. You need to make sure that sublime is launched from a terminal where that is the case.

**Comment by eboatwright** [comment]
Running the "subl" command fixed it, thank you! I'll try to get that sorted out. Thanks again!
